# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a86312eee92cdd2dc8876f3b06562c701886dd1026acf5e2f578ca974dd5ddd3ce069e787d6fa06d33d4686f7afc964d800404785c4f014f3ae5eb140f8cb8e0

test:
  secret_key_base: 2dd04a82666cb138065a9afa50a790969e91d79f8e5d94ab46c108167474ac9e10be480e3baed49af2f68a59d0147bca47c4762f6637e161673c37ed0205bb2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
